from alembic import op
from sqlalchemy.sql.schema import Column
from sqlalchemy.sql.schema import ForeignKeyConstraint
from sqlalchemy.sql.schema import MetaData
from sqlalchemy.sql.schema import PrimaryKeyConstraint
from sqlalchemy.sql.schema import Table
from sqlalchemy.sql.sqltypes import BigInteger
from sqlalchemy.sql.sqltypes import Boolean
from sqlalchemy.sql.sqltypes import DateTime
from sqlalchemy.sql.sqltypes import Float
from sqlalchemy.sql.sqltypes import Integer
from sqlmodel.sql.sqltypes import AutoString

# revision identifiers, used by Alembic.
revision = 'aNxqjvhGaR0u_hAenBpXJVQ'
down_revision = 'DilrcsvdQyGQ9NgsGhj6VQ'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by rewire_sqlmodel - please adjust! ###
    with op.batch_alter_table('mailing', schema=None) as batch_op:
        batch_op.alter_column(
            'challenge_id',
            type_=AutoString(),
            nullable=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by rewire_sqlmodel - please adjust! ###
    with op.batch_alter_table('mailing', schema=None) as batch_op:
        batch_op.alter_column(
            'challenge_id',
            type_=AutoString(),
            nullable=True,
        )
    # ### end Alembic commands ###


_Meta = MetaData()
schema = {
    'challenge': Table(
        'challenge',
        _Meta,
        Column(
            'id',
            AutoString(),
            primary_key=True,
            nullable=False,
        ),
        Column(
            'name',
            AutoString(),
            nullable=False,
        ),
        Column(
            'description',
            AutoString(),
            nullable=False,
        ),
        Column(
            'scene_width',
            Float(),
            nullable=False,
        ),
        Column(
            'scene_height',
            Float(),
            nullable=False,
        ),
        PrimaryKeyConstraint(
            'id',
        ),
    ),
    'challengeelement': Table(
        'challengeelement',
        _Meta,
        Column(
            'id',
            AutoString(),
            primary_key=True,
            nullable=False,
        ),
        Column(
            'challenge_id',
            AutoString(),
            nullable=False,
        ),
        Column(
            'name',
            AutoString(),
            nullable=False,
        ),
        Column(
            'width',
            Float(),
            nullable=False,
        ),
        Column(
            'target_x',
            Float(),
            nullable=False,
        ),
        Column(
            'target_y',
            Float(),
            nullable=False,
        ),
        ForeignKeyConstraint(
            ['challenge_id'],
            [
                'challenge.id',
            ],
            name='fk_challengeelement_challenge_id_challenge',
        ),
        PrimaryKeyConstraint(
            'id',
        ),
    ),
    'mailing': Table(
        'mailing',
        _Meta,
        Column(
            'id',
            Integer(),
            primary_key=True,
            nullable=False,
        ),
        Column(
            'message_text',
            AutoString(),
            nullable=False,
        ),
        Column(
            'button_text',
            AutoString(),
            nullable=False,
        ),
        Column(
            'button_url',
            AutoString(),
            nullable=False,
        ),
        Column(
            'challenge_id',
            AutoString(),
            nullable=False,
        ),
        ForeignKeyConstraint(
            ['challenge_id'],
            [
                'challenge.id',
            ],
            name='fk_mailing_challenge_id_challenge',
        ),
        PrimaryKeyConstraint(
            'id',
        ),
    ),
    'user': Table(
        'user',
        _Meta,
        Column(
            'id',
            BigInteger(),
            primary_key=True,
            nullable=False,
        ),
        Column(
            'created_at',
            DateTime(),
            nullable=False,
        ),
        Column(
            'name',
            AutoString(),
            nullable=False,
        ),
        Column(
            'username',
            AutoString(),
            nullable=True,
        ),
        Column(
            'avatar_url',
            AutoString(),
            nullable=True,
        ),
        Column(
            'average_score',
            Float(),
            nullable=False,
        ),
        Column(
            'last_completed_at',
            DateTime(),
            nullable=True,
        ),
        Column(
            'last_challenge_message_id',
            AutoString(),
            nullable=True,
        ),
        Column(
            'received_certificate',
            Boolean(),
            nullable=False,
        ),
        Column(
            'current_challenge_id',
            AutoString(),
            nullable=True,
        ),
        ForeignKeyConstraint(
            ['current_challenge_id'],
            [
                'challenge.id',
            ],
            name='fk_user_current_challenge_id_challenge',
        ),
        PrimaryKeyConstraint(
            'id',
        ),
    ),
}
