from alembic import op
from sqlalchemy.sql.elements import quoted_name
from sqlalchemy.sql.schema import Table
from sqlalchemy.sql.schema import MetaData
from sqlalchemy.sql.schema import Column
from sqlmodel.sql.sqltypes import AutoString
from sqlalchemy.sql.sqltypes import Float
from sqlalchemy.sql.schema import PrimaryKeyConstraint
from sqlalchemy.sql.schema import ForeignKeyConstraint
from sqlalchemy.sql.sqltypes import BigInteger
from sqlalchemy.sql.sqltypes import DateTime


# revision identifiers, used by Alembic.
revision = 'CAx3dsrfzQoSgJq2Q7eTstg'
down_revision = 'VyOzeY9GPTK6EDehiRLQBA'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by rewire_sqlmodel - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
            Column(
                'last_challenge_message_id',
                AutoString(),
                nullable=True,
            ),
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by rewire_sqlmodel - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_challenge_message_id')
    # ### end Alembic commands ###



_Meta = MetaData()
schema = {
    'challenge': Table(
        'challenge',
        _Meta,
        Column(
            'id',
            AutoString(),
            primary_key=True,
            nullable=False,
        ),
        Column(
            'name',
            AutoString(),
            nullable=False,
        ),
        Column(
            'description',
            AutoString(),
            nullable=False,
        ),
        Column(
            'scene_width',
            Float(),
            nullable=False,
        ),
        PrimaryKeyConstraint(
            'id',
        ),
    ),
    'challengeelement': Table(
        'challengeelement',
        _Meta,
        Column(
            'id',
            AutoString(),
            primary_key=True,
            nullable=False,
        ),
        Column(
            'challenge_id',
            AutoString(),
            nullable=False,
        ),
        Column(
            'name',
            AutoString(),
            nullable=False,
        ),
        Column(
            'width',
            Float(),
            nullable=False,
        ),
        Column(
            'target_x',
            Float(),
            nullable=False,
        ),
        Column(
            'target_y',
            Float(),
            nullable=False,
        ),
        ForeignKeyConstraint(
            ['challenge_id'],
            [
                'challenge.id',
            ],
            name='fk_challengeelement_challenge_id_challenge',
        ),
        PrimaryKeyConstraint(
            'id',
        ),
    ),
    'user': Table(
        'user',
        _Meta,
        Column(
            'id',
            BigInteger(),
            primary_key=True,
            nullable=False,
        ),
        Column(
            'created_at',
            DateTime(),
            nullable=False,
        ),
        Column(
            'name',
            AutoString(),
            nullable=False,
        ),
        Column(
            'username',
            AutoString(),
            nullable=True,
        ),
        Column(
            'avatar_url',
            AutoString(),
            nullable=True,
        ),
        Column(
            'average_score',
            Float(),
            nullable=False,
        ),
        Column(
            'last_completed_at',
            DateTime(),
            nullable=True,
        ),
        Column(
            'last_challenge_message_id',
            AutoString(),
            nullable=True,
        ),
        Column(
            'current_challenge_id',
            AutoString(),
            nullable=True,
        ),
        ForeignKeyConstraint(
            ['current_challenge_id'],
            [
                'challenge.id',
            ],
            name='fk_user_current_challenge_id_challenge',
        ),
        PrimaryKeyConstraint(
            'id',
        ),
    ),
}
